export const MUTATION_KEYS = {
  LOGIN: 'MK_LOGIN',
  CREATE_FOLDER: 'MK_CREATE_FOLDER',
  UPDATE_FOLDER: 'MK_UPDATE_FOLDER',
  REMOVE_FOLDER: 'MK_REMOVE_FOLDER',

  UPLOAD_RESUME: 'MK_UPLOAD_RESUME',
  REMOVE_RESUME: 'MK_REMOVE_RESUME',
}
