export const QUERY_KEYS = {
  FOLDER_LIST: 'QK_FOLDER_LIST',
  KEYWORD_LIST: 'QK_KEYWORDLIST',
  SEARCH_RESUME: 'QK_SEARCH_RESUME',
  RESUME_DETAIL: 'QK_RESUME_DETAIL',
  RESUME_FILE: 'QK_RESUME_FILE',
}
